steps:
  - name: ":rspec:"
    command: "scripts/ci/parallel_specs.sh"
    artifact_paths: "log/**/*"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: app
      RAILS_ENV: test
    parallelism: 20
    agents:
      queue: default
